# Generated by Django 2.2.3 on 2019-08-06 22:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='env_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_water_setting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('user_food_setting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rfid')),
            ],
        ),
        migrations.CreateModel(
            name='pet_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_drink', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('food_eat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rfid')),
            ],
        ),
    ]
