# Generated by Django 2.2.4 on 2019-10-10 12:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('kCal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device_info')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.SmallIntegerField(blank=True, choices=[(1, 'Cat'), (2, 'Dog')], default=0, null=True)),
                ('cat_statue', models.DecimalField(blank=True, choices=[(2.5, 'Kitten'), (1.4, 'Neutered'), (1.2, 'Intact'), (1.0, 'Inactive/obese prone'), (0.95, 'Weight loss')], decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('dog_statue', models.DecimalField(blank=True, choices=[(3, '0-4 months'), (2, '4 months to adult'), (1.6, 'Neutered'), (1.8, 'Intact'), (1.3, 'Inactive/obese prone'), (1.0, 'Weight loss'), (1.5, 'Weight gain'), (3.5, 'Active, working dogs')], decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('suggest_water_drinking_daily', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('suggest_feed_amount_daily', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('user_water_drinking_setting_daily', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('user_feed_amount_setting_daily', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('food_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag_Info')),
                ('food_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food_type')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device_info')),
            ],
        ),
        migrations.CreateModel(
            name='pet_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_drink', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('food_eat', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag_Info')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device_info')),
            ],
        ),
        migrations.CreateModel(
            name='env_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device_info')),
            ],
        ),
    ]
