# Generated by Django 2.2.3 on 2019-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env_info',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='env_location',
        ),
    ]
