# Generated by Django 2.2.3 on 2019-08-10 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_info',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
