# Generated by Django 2.2.3 on 2019-08-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
