# Generated by Django 2.2.3 on 2019-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190730_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='gettemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='env_info',
            options={},
        ),
    ]
