# Generated by Django 2.2.4 on 2019-08-17 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190813_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_setting',
            old_name='user_food_setting',
            new_name='user_food_setting_daily',
        ),
        migrations.RenameField(
            model_name='user_setting',
            old_name='user_water_setting',
            new_name='user_water_setting_daily',
        ),
        migrations.AddField(
            model_name='tag_info',
            name='suggest_feed_amount_daily',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tag_info',
            name='suggest_water_drinking_daily',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
