# Generated by Django 2.2.4 on 2019-11-13 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191018_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servo', models.CharField(default='servo', max_length=20)),
                ('x_angle', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3)),
                ('y_angle', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3)),
            ],
        ),
    ]
