# Generated by Django 2.2.4 on 2019-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='x_angle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='control',
            name='y_angle',
            field=models.IntegerField(),
        ),
    ]
