# Generated by Django 2.2.4 on 2019-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190818_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_info',
            name='category',
            field=models.SmallIntegerField(choices=[('0', 'Null'), ('1', 'Cat'), ('2', 'Dog')], default=0),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag_info',
            name='nickname',
            field=models.CharField(blank=True, default='Null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_setting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
