# Generated by Django 2.2.3 on 2019-07-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190731_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gettemp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gettemp',
            name='updated_at',
        ),
    ]
