# Generated by Django 2.2.3 on 2019-07-31 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190731_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettemp',
            name='temp_id',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
