# Generated by Django 2.2.3 on 2019-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gettemp_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettemp',
            name='temp_id',
            field=models.IntegerField(),
        ),
    ]
