# Generated by Django 2.2.3 on 2019-07-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190731_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gettemp',
        ),
    ]
