# Generated by Django 2.2.4 on 2019-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190819_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_info',
            name='cat_statue',
            field=models.FloatField(blank=True, choices=[(1.1, 'Cat'), (2, 'Dog')], null=True),
        ),
    ]
