# Generated by Django 2.2.4 on 2019-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190819_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_info',
            name='cat_statue',
            field=models.FloatField(blank=True, choices=[(2.5, 'Kitten'), (1.4, 'Neutered'), (1.2, 'Intact'), (1.0, 'Inactive/obese prone'), (0.95, 'Weight loss')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tag_info',
            name='category',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Cat'), (2, 'Dog')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tag_info',
            name='dog_statue',
            field=models.FloatField(blank=True, choices=[(3, '0-4 months'), (2, '4 months to adult'), (1.6, 'Neutered'), (1.8, 'Intact'), (1.3, 'Inactive/obese prone'), (1.0, 'Weight loss'), (1.5, 'Weight gain'), (3.5, 'Active, working dogs')], default=0, null=True),
        ),
    ]
