# Generated by Django 2.2.4 on 2019-08-18 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190819_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_info',
            name='per',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
