# Generated by Django 2.2.4 on 2019-08-18 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tag_info_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_info',
            name='cat_statue',
            field=models.DecimalField(blank=True, choices=[(2.5, 'Kitten'), (1.4, 'Neutered'), (1.2, 'Intact'), (1.0, 'Inactive/obese prone'), (0.95, 'Weight loss')], decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tag_info',
            name='dog_statue',
            field=models.DecimalField(blank=True, choices=[(3, '0-4 months'), (2, '4 months to adult'), (1.6, 'Neutered'), (1.8, 'Intact'), (1.3, 'Inactive/obese prone'), (1.0, 'Weight loss'), (1.5, 'Weight gain'), (3.5, 'Active, working dogs')], decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
