# Generated by Django 2.2.4 on 2019-08-19 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190819_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
