# Generated by Django 2.2.4 on 2019-08-20 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tag_info_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_info',
            name='user_feed_amount_setting_daily',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tag_info',
            name='user_water_drinking_setting_daily',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
