# Generated by Django 2.2.3 on 2019-08-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190820_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_setting',
            old_name='user_food_setting_daily',
            new_name='user_food_setting',
        ),
        migrations.RemoveField(
            model_name='user_setting',
            name='user_water_setting_daily',
        ),
    ]
