# Generated by Django 2.2.3 on 2019-08-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190821_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_setting',
            old_name='user_food_setting',
            new_name='food_ammount',
        ),
    ]
