# Generated by Django 2.2.3 on 2019-08-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190823_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_setting',
            name='schedule_time',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
