# Generated by Django 2.2.3 on 2019-08-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_setting_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_setting',
            name='schedule_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
