# Generated by Django 2.2.3 on 2019-08-22 22:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190823_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_setting',
            name='food_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='user_setting',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
