# Generated by Django 2.2.3 on 2019-08-22 22:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190823_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('kCal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='food_eat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='water_drink',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='user_setting',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
