# Generated by Django 2.2.3 on 2019-08-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_user_setting_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_setting',
            name='food_Name',
        ),
    ]
