# Generated by Django 2.2.3 on 2019-08-22 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_user_setting_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_setting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user_setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
