# Generated by Django 2.2.3 on 2019-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190823_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_setting',
            old_name='food_ammount',
            new_name='food_amount',
        ),
        migrations.AlterField(
            model_name='tag_info',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
