# Generated by Django 2.2.3 on 2019-08-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_user_setting_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food_type',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user_setting',
            name='created_at',
        ),
    ]
