# Generated by Django 2.2.4 on 2019-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190928_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_type',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
