# Generated by Django 2.2.4 on 2019-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190928_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='active_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
