# Generated by Django 2.2.4 on 2019-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190929_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='env_info',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
