# Generated by Django 2.2.4 on 2019-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_env_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env_info',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
