# Generated by Django 2.2.4 on 2019-09-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190930_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='env_info',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
