# Generated by Django 2.2.4 on 2019-09-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190930_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='env_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='env_info',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='env_info',
            name='location_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.env_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='env_info',
            name='location_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.env_location'),
            preserve_default=False,
        ),
    ]
