# Generated by Django 2.2.4 on 2019-09-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190930_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env_info',
            name='location_name',
        ),
        migrations.AlterField(
            model_name='env_info',
            name='location_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.env_location'),
        ),
        migrations.AlterField(
            model_name='env_location',
            name='location_code',
            field=models.CharField(max_length=100),
        ),
    ]
