# Generated by Django 2.2.4 on 2019-09-30 08:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190930_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env_info',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='env_info',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='env_location',
            name='location_name',
        ),
        migrations.AddField(
            model_name='env_info',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='env_location',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='env_location',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='location_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='env_location',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='env_location',
            name='location_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.env_info'),
        ),
        migrations.AlterField(
            model_name='env_location',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
