# Generated by Django 2.2.4 on 2019-10-01 03:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190930_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Tag', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='env_info',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='env_info',
            name='location_name',
        ),
        migrations.AddField(
            model_name='env_info',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='env_info',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='env_info',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='env_location',
        ),
        migrations.AddField(
            model_name='env_info',
            name='Tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.device_info'),
            preserve_default=False,
        ),
    ]
