# Generated by Django 2.2.4 on 2019-10-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20191001_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_info',
            old_name='Tag',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='device_info',
            old_name='Name',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='env_info',
            old_name='Tag',
            new_name='device_id',
        ),
    ]
